linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - golint
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen

linters-settings:
  lll:
    line-length: 160
  cyclop:
    max-complexity: 12
  revive:
    ignore-generated-header: true
    severity: error
    rules:
      - name: context-keys-type      
      - name: time-naming             
      - name: var-declaration         
      - name: unexported-return       
      - name: errorf                  
      - name: blank-imports           
      - name: context-as-argument     
      - name: dot-imports             
      - name: error-return            
      - name: error-strings           
      - name: error-naming            
      - name: if-return               
      - name: increment-decrement     
      - name: package-comments        
      - name: range                   
      - name: receiver-naming         
      - name: indent-error-flow       
      - name: empty-block             
      - name: superfluous-else        
      - name: confusing-naming        
      - name: get-return              
      - name: modifies-parameter      
      - name: confusing-results       
      - name: deep-exit               
      - name: unused-parameter        
      - name: unreachable-code        
      - name: flag-parameter          
      - name: unnecessary-stmt        
      - name: struct-tag              
      - name: modifies-value-receiver 
      - name: constant-logical-expr   
      - name: bool-literal-in-expr    
      - name: redefines-builtin-id    
      - name: range-val-in-closure    
      - name: range-val-address       
      - name: waitgroup-by-value      
      - name: atomic                  
      - name: empty-lines             
      - name: call-to-gc              
      - name: duplicated-imports      
      - name: import-shadowing        
      - name: bare-return             
      - name: unused-receiver         
      - name: string-of-int           
      - name: early-return            
      - name: unconditional-recursion 
      - name: identical-branches      
      - name: unexported-naming       
      - name: nested-structs          
      - name: useless-break           
      - name: cyclomatic
        arguments: [12]
      - name: unhandled-error
        arguments: ["fmt.Printf", "fmt.Fprintf", "fmt.Sprintf", "fmt.Fprintln"]
      - name: cognitive-complexity
        arguments: [16]
      - name: line-length-limit
        arguments: [160]

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
