// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/view/layout.qtpl:1
package view

//line internal/view/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/view/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/view/layout.qtpl:1
func StreamLayout(qw422016 *qt422016.Writer, title string, csrfToken string, content string) {
//line internal/view/layout.qtpl:1
	qw422016.N().S(`
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="csrf-token" content="`)
//line internal/view/layout.qtpl:7
	qw422016.E().S(csrfToken)
//line internal/view/layout.qtpl:7
	qw422016.N().S(`">
      <title>`)
//line internal/view/layout.qtpl:8
	qw422016.E().S(title)
//line internal/view/layout.qtpl:8
	qw422016.N().S(`</title>
      <link rel="stylesheet" type="text/css" href="/css/uikit.min.css">
    </head>
    <body>
      `)
//line internal/view/layout.qtpl:12
	qw422016.N().S(content)
//line internal/view/layout.qtpl:12
	qw422016.N().S(`
      <script src="/js/uikit.min.js"></script>
      <script src="/js/uikit-icons.min.js"></script>
    </body>
  </html>
`)
//line internal/view/layout.qtpl:17
}

//line internal/view/layout.qtpl:17
func WriteLayout(qq422016 qtio422016.Writer, title string, csrfToken string, content string) {
//line internal/view/layout.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/view/layout.qtpl:17
	StreamLayout(qw422016, title, csrfToken, content)
//line internal/view/layout.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line internal/view/layout.qtpl:17
}

//line internal/view/layout.qtpl:17
func Layout(title string, csrfToken string, content string) string {
//line internal/view/layout.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/view/layout.qtpl:17
	WriteLayout(qb422016, title, csrfToken, content)
//line internal/view/layout.qtpl:17
	qs422016 := string(qb422016.B)
//line internal/view/layout.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/view/layout.qtpl:17
	return qs422016
//line internal/view/layout.qtpl:17
}
