// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/view/login.qtpl:1
package view

//line internal/view/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/view/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/view/login.qtpl:1
func StreamLogin(qw422016 *qt422016.Writer, disableRegistration bool, csrfToken string, username string, errorMessage string) {
//line internal/view/login.qtpl:1
	qw422016.N().S(`
  <div class="uk-container">
    <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-margin-large-top uk-width-1-1 uk-width-1-3@l uk-margin-auto@l">
      <h3 class="uk-card-title">archmark</h3>
      <form method="post" action="/login">
        <input type="hidden" name="csrf" value="`)
//line internal/view/login.qtpl:6
	qw422016.E().S(csrfToken)
//line internal/view/login.qtpl:6
	qw422016.N().S(`">
        <div class="uk-margin">
          <input class="uk-input" type="text" name="username" placeholder="Username" value="`)
//line internal/view/login.qtpl:8
	qw422016.E().S(username)
//line internal/view/login.qtpl:8
	qw422016.N().S(`">
        </div>
        <div class="uk-margin">
          <input class="uk-input" type="password" name="password" placeholder="Password">
        </div>
        <input type="submit" value="Login" class="uk-button uk-button-primary uk-width-1-1 uk-margin-bottom">
        `)
//line internal/view/login.qtpl:14
	if errorMessage != "" {
//line internal/view/login.qtpl:14
		qw422016.N().S(`
          <div uk-alert="" class="uk-margin-remove">
            <p class="uk-margin-remove uk-text-center">`)
//line internal/view/login.qtpl:16
		qw422016.E().S(errorMessage)
//line internal/view/login.qtpl:16
		qw422016.N().S(`</p>
          </div>
        `)
//line internal/view/login.qtpl:18
	}
//line internal/view/login.qtpl:18
	qw422016.N().S(`
      </form>
      `)
//line internal/view/login.qtpl:20
	if !disableRegistration {
//line internal/view/login.qtpl:20
		qw422016.N().S(`
        <div class="uk-flex uk-flex-row uk-flex-center">
          <a class="uk-link-muted" href="/register">register new user</a>
        </div>
      `)
//line internal/view/login.qtpl:24
	}
//line internal/view/login.qtpl:24
	qw422016.N().S(`
    </div>
  </div>
`)
//line internal/view/login.qtpl:27
}

//line internal/view/login.qtpl:27
func WriteLogin(qq422016 qtio422016.Writer, disableRegistration bool, csrfToken string, username string, errorMessage string) {
//line internal/view/login.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/view/login.qtpl:27
	StreamLogin(qw422016, disableRegistration, csrfToken, username, errorMessage)
//line internal/view/login.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line internal/view/login.qtpl:27
}

//line internal/view/login.qtpl:27
func Login(disableRegistration bool, csrfToken string, username string, errorMessage string) string {
//line internal/view/login.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/view/login.qtpl:27
	WriteLogin(qb422016, disableRegistration, csrfToken, username, errorMessage)
//line internal/view/login.qtpl:27
	qs422016 := string(qb422016.B)
//line internal/view/login.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/view/login.qtpl:27
	return qs422016
//line internal/view/login.qtpl:27
}
