// Code generated by qtc from "register.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/view/register.qtpl:1
package view

//line internal/view/register.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/view/register.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/view/register.qtpl:1
func StreamRegister(qw422016 *qt422016.Writer, csrfToken string, name string, username string, errorMessage string) {
//line internal/view/register.qtpl:1
	qw422016.N().S(`
  <div class="uk-container">
    <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-margin-large-top uk-width-1-1 uk-width-1-3@l uk-margin-auto@l">
      <h3 class="uk-card-title">archmark</h3>
      <form method="post" action="/register">
        <input type="hidden" name="csrf" value="`)
//line internal/view/register.qtpl:6
	qw422016.E().S(csrfToken)
//line internal/view/register.qtpl:6
	qw422016.N().S(`">
        <div class="uk-margin">
          <input class="uk-input" type="text" name="name" placeholder="Name" value="`)
//line internal/view/register.qtpl:8
	qw422016.E().S(name)
//line internal/view/register.qtpl:8
	qw422016.N().S(`">
        </div>
        <div class="uk-margin">
          <input class="uk-input" type="text" name="username" placeholder="Username" value="`)
//line internal/view/register.qtpl:11
	qw422016.E().S(username)
//line internal/view/register.qtpl:11
	qw422016.N().S(`">
        </div>
        <div class="uk-margin">
          <input class="uk-input" type="password" name="password" placeholder="Password">
        </div>
        <div class="uk-margin">
          <input class="uk-input" type="password" name="password_confirmation" placeholder="Password (again)">
        </div>
        <input type="submit" value="Register" class="uk-button uk-button-primary uk-width-1-1 uk-margin-bottom">
        `)
//line internal/view/register.qtpl:20
	if errorMessage != "" {
//line internal/view/register.qtpl:20
		qw422016.N().S(`
          <div uk-alert="" class="uk-margin-remove">
            <p class="uk-margin-remove uk-text-center">`)
//line internal/view/register.qtpl:22
		qw422016.E().S(errorMessage)
//line internal/view/register.qtpl:22
		qw422016.N().S(`</p>
          </div>
        `)
//line internal/view/register.qtpl:24
	}
//line internal/view/register.qtpl:24
	qw422016.N().S(`
      </form>
      <div class="uk-flex uk-flex-row uk-flex-center">
        <a class="uk-link-muted" href="/login">login</a>
      </div>
    </div>
  </div>
`)
//line internal/view/register.qtpl:31
}

//line internal/view/register.qtpl:31
func WriteRegister(qq422016 qtio422016.Writer, csrfToken string, name string, username string, errorMessage string) {
//line internal/view/register.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/view/register.qtpl:31
	StreamRegister(qw422016, csrfToken, name, username, errorMessage)
//line internal/view/register.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line internal/view/register.qtpl:31
}

//line internal/view/register.qtpl:31
func Register(csrfToken string, name string, username string, errorMessage string) string {
//line internal/view/register.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/view/register.qtpl:31
	WriteRegister(qb422016, csrfToken, name, username, errorMessage)
//line internal/view/register.qtpl:31
	qs422016 := string(qb422016.B)
//line internal/view/register.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/view/register.qtpl:31
	return qs422016
//line internal/view/register.qtpl:31
}
