package localize

//nolint:gochecknoglobals
var englishStrings = map[StringIdentifier]string{
	ActiveTokens:          "Active Tokens",
	AddWarning:            "Please note that it might take a while for the archive to be generated. In the meantime, you can use the 'original' link.",
	APITokens:             "API Tokens",
	Add:                   "Add",
	AddNew:                "New bookmark",
	AddedTimeStamp:        "Added at %s",
	Bookmarks:             "Bookmarks",
	Cancel:                "Cancel",
	CreateNewToken:        "Create new token",
	Delete:                "Delete",
	DeleteBookmarkTitle:   "Delete bookmark",
	DeleteBookmarkWarning: "Are you sure you want to delete this bookmark?",
	InternalServerError:   "Internal server error. Please try again later.",
	LanguageLabel:         "Language",
	NoBookmarksFound:      "No bookmarks found",
	OpenOriginalLink:      "Open original link",
	PasteURLHere:          "Paste URL here...",
	Pending:               "loading",
	SaveSettings:          "Save settings",
	SearchPlaceholder:     "Type query and hit Enter to search",
	SelectLanguage:        "Choose the language for the app",
	SelectTheme:           "Choose a theme for the app",
	Settings:              "Settings",
	ThemeDark:             "Dark",
	ThemeLabel:            "Theme",
	ThemeLight:            "Light",
}
