package localize

//nolint:gochecknoglobals
var malayalamStrings = map[StringIdentifier]string{
	ActiveTokens:          "സജീവ ടോക്കണുകൾ",
	AddWarning:            "ആർക്കൈവ് ജനറേറ്റുചെയ്യുന്നതിന് കുറച്ച് സമയമെടുത്തേക്കാം എന്നത് ശ്രദ്ധിക്കുക. അതിനിടയിൽ, നിങ്ങൾക്ക് 'ഒറിജിനൽ' ലിങ്ക് ഉപയോഗിക്കാം. ",
	APITokens:             "API ടോക്കണുകൾ ",
	Add:                   "ചേർക്കുക",
	AddNew:                "പുതിയ ബുക്ക്മാർക്ക് ",
	AddedTimeStamp:        "%s-ന് സൃഷ്ടിച്ചു ",
	Bookmarks:             "ബുക്ക്മാർക്കുകൾ",
	Cancel:                "വേണ്ട",
	CreateNewToken:        "പുതിയ ടോക്കൺ സൃഷ്ടിക്കുക ",
	Delete:                "ഇല്ലാതാക്കുക",
	DeleteBookmarkTitle:   "ബുക്ക്മാർക്ക് ഇല്ലാതാക്കുക",
	DeleteBookmarkWarning: "ഇത് ഇല്ലാതാക്കണമെന്ന് തീർച്ചയാണോ?",
	InternalServerError:   "സെർവർ തകരാർ. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.",
	LanguageLabel:         "ഭാഷ",
	NoBookmarksFound:      "ബുക്ക് മാർക്കുകൾ കണ്ടെത്തിയില്ല",
	OpenOriginalLink:      "യഥാർത്ഥ ലിങ്ക് തുറക്കുക ",
	PasteURLHere:          "URL ഇവിടെ ഇടുക...",
	Pending:               "ലോഡിംഗ്",
	SaveSettings:          "സജ്ജീകരണങ്ങൾ സംരക്ഷിക്കുക",
	SearchPlaceholder:     "തിരയാൻ, ഇവിടെ ടൈപ്പ് ചെയ്യുക",
	SelectLanguage:        "ആപ്പിനുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക",
	SelectTheme:           "ആപ്പിനായി ഒരു തീം തിരഞ്ഞെടുക്കുക",
	Settings:              "സജ്ജീകരണങ്ങൾ",
	ThemeDark:             "ഇരുണ്ട",
	ThemeLabel:            "തീം",
	ThemeLight:            "ലൈറ്റ്",
}
