// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbx

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID                uuid.UUID
	Name              string
	Email             string
	EncryptedPassword string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
