// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/home.qtpl:1
package view

//line view/home.qtpl:1
import "github.com/sparkymat/archmark/presenter"

//line view/home.qtpl:2
import "fmt"

//line view/home.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/home.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/home.qtpl:4
func StreamHome(qw422016 *qt422016.Writer, csrfToken string, showSearchHeader bool, searchQuery string, bookmarksList presenter.BookmarksList) {
//line view/home.qtpl:4
	qw422016.N().S(`
  <div class="container mx-auto">
    <div class="flex flex-col mt-4 mb-16">
      <form action="/" method="GET" class="flex flex-row">
        <input type="text" name="q" class="flex-grow text-xl mt-2 p-2 border outline-white" placeholder="Type query and hit Enter to search" autofocus>
      </form>
      `)
//line view/home.qtpl:10
	if showSearchHeader {
//line view/home.qtpl:10
		qw422016.N().S(`
        <div class="px-4 py-2 mt-4 bg-gray-200 rounded-sm border border-dashed flex flex-row justify-between items-center">
          <span class="text-xl italic">Showing results for '`)
//line view/home.qtpl:12
		qw422016.E().S(searchQuery)
//line view/home.qtpl:12
		qw422016.N().S(`'</span>
          <a href="/" class="text-lg text-white bg-gray-600 hover:bg-gray-800 rounded px-4 py-2 shadow-md">Clear</a>
        </div>
      `)
//line view/home.qtpl:15
	}
//line view/home.qtpl:15
	qw422016.N().S(`
      `)
//line view/home.qtpl:16
	if len(bookmarksList.Bookmarks) == 0 {
//line view/home.qtpl:16
		qw422016.N().S(`
        <div class="flex flex-col items-center mt-16">
          <p class="border border-dashed border-gray-400 py-4 px-8 text-xl text-gray-600">No bookmarks found</p>
        </div>
      `)
//line view/home.qtpl:20
	}
//line view/home.qtpl:20
	qw422016.N().S(`
      <ul class="my-2">
        `)
//line view/home.qtpl:22
	for _, bookmark := range bookmarksList.Bookmarks {
//line view/home.qtpl:22
		qw422016.N().S(`
          <li class="py-4">
            `)
//line view/home.qtpl:24
		if bookmark.IsActive {
//line view/home.qtpl:24
			qw422016.N().S(`
              <a class="flex flex-row items-center" href="`)
//line view/home.qtpl:25
			qw422016.E().S(bookmark.URL)
//line view/home.qtpl:25
			qw422016.N().S(`" target="_blank">
                <div class="text-md">`)
//line view/home.qtpl:26
			qw422016.N().S(fmt.Sprintf("%d.", bookmark.Index))
//line view/home.qtpl:26
			qw422016.N().S(`</div>
                <div class="text-xl ml-2">`)
//line view/home.qtpl:27
			qw422016.E().S(bookmark.Title)
//line view/home.qtpl:27
			qw422016.N().S(`</div>
              </a>
            `)
//line view/home.qtpl:29
		} else {
//line view/home.qtpl:29
			qw422016.N().S(`
              <a class="flex flex-row items-center font-light" href="#">
                <div class="text-md">`)
//line view/home.qtpl:31
			qw422016.N().S(fmt.Sprintf("%d.", bookmark.Index))
//line view/home.qtpl:31
			qw422016.N().S(`</div>
                <div class="text-xl ml-2">[pending] `)
//line view/home.qtpl:32
			qw422016.E().S(bookmark.Title)
//line view/home.qtpl:32
			qw422016.N().S(`</div>
              </a>
            `)
//line view/home.qtpl:34
		}
//line view/home.qtpl:34
		qw422016.N().S(`
            <div class="">
              <span class="text-sm text-gray-400 mr-2">added `)
//line view/home.qtpl:36
		qw422016.E().S(bookmark.TimeSince)
//line view/home.qtpl:36
		qw422016.N().S(`</span>
              <span>•</span>
              <a href="`)
//line view/home.qtpl:38
		qw422016.E().S(bookmark.OriginalURL)
//line view/home.qtpl:38
		qw422016.N().S(`" target="_blank" class="text-sm text-gray-400 hover:text-blue-400 border-b-2 border-dashed mx-2">open original link</a>
              <span>•</span>
              <a href="javascript:showBookmarkDeleteModal(`)
//line view/home.qtpl:40
		qw422016.N().DUL(bookmark.ID)
//line view/home.qtpl:40
		qw422016.N().S(`)" class="text-sm text-gray-400 hover:text-red-400 border-b-2 border-dashed mx-2">delete</a>
            </div>
          </li>
        `)
//line view/home.qtpl:43
	}
//line view/home.qtpl:43
	qw422016.N().S(`
      </ul>
      `)
//line view/home.qtpl:45
	if bookmarksList.ShowNextLink {
//line view/home.qtpl:45
		qw422016.N().S(`
        <div class="flex flex-row p-2 mx-auto">
          <a href="`)
//line view/home.qtpl:47
		qw422016.E().S(bookmarksList.NextPageLink)
//line view/home.qtpl:47
		qw422016.N().S(`" class="text-lg text-white bg-gray-600 hover:bg-gray-800 rounded px-5 py-2 shadow-md">Show more</a>
        </div>
      `)
//line view/home.qtpl:49
	}
//line view/home.qtpl:49
	qw422016.N().S(`
    </div>
  </div>
  <div class="min-w-screen h-screen animated fadeIn faster fixed left-0 top-0 flex justify-center items-center inset-0 z-50 outline-none focus:outline-none bg-no-repeat bg-center bg-cover" id="bookmark-delete-modal" style="display:none;">
   	<div class="absolute bg-black opacity-80 inset-0 z-0" onClick="hideBookmarkDeleteModal()"></div>
    <div class="w-full max-w-lg p-2 relative mx-auto my-auto rounded shadow-lg bg-white">
      <div class="">
        <div class="text-center p-2 flex-auto justify-center">
          <h3 class="text-lg font-bold py-4 ">Bookmark delete</h3>
          <p class="text-md text-gray-400 px-4">Are you sure you want to delete this bookmark?</p>
        </div>
        <form action="/bookmarks/__ID__/destroy" method="POST" id="bookmark-delete-form">
          <input type="hidden" name="csrf" value="`)
//line view/home.qtpl:61
	qw422016.E().S(csrfToken)
//line view/home.qtpl:61
	qw422016.N().S(`">
          <div class="p-3 mt-2 flex flex-row justify-end">
            <a href="javascript:hideBookmarkDeleteModal()" class="text-lg text-gray-white bg-gray-300 hover:bg-gray-400 rounded px-5 py-2 mr-2 shadow-md">Cancel</a>
            <input type="submit" value="Delete" class="text-lg text-white bg-red-600 hover:bg-red-800 rounded px-5 py-2 shadow-md">
          </div>
        </form>
      </div>
    </div>
  </div>
`)
//line view/home.qtpl:70
}

//line view/home.qtpl:70
func WriteHome(qq422016 qtio422016.Writer, csrfToken string, showSearchHeader bool, searchQuery string, bookmarksList presenter.BookmarksList) {
//line view/home.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/home.qtpl:70
	StreamHome(qw422016, csrfToken, showSearchHeader, searchQuery, bookmarksList)
//line view/home.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line view/home.qtpl:70
}

//line view/home.qtpl:70
func Home(csrfToken string, showSearchHeader bool, searchQuery string, bookmarksList presenter.BookmarksList) string {
//line view/home.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line view/home.qtpl:70
	WriteHome(qb422016, csrfToken, showSearchHeader, searchQuery, bookmarksList)
//line view/home.qtpl:70
	qs422016 := string(qb422016.B)
//line view/home.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line view/home.qtpl:70
	return qs422016
//line view/home.qtpl:70
}
