// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/home.qtpl:1
package view

//line view/home.qtpl:1
import "github.com/sparkymat/archmark/presenter"

//line view/home.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/home.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/home.qtpl:3
func StreamHome(qw422016 *qt422016.Writer, bookmarks []presenter.Bookmark) {
//line view/home.qtpl:3
	qw422016.N().S(`
  <div>
    <input type="text">
    <ul>
      `)
//line view/home.qtpl:7
	for _, bookmark := range bookmarks {
//line view/home.qtpl:7
		qw422016.N().S(`
        <li>
          <a href="`)
//line view/home.qtpl:9
		qw422016.E().S(bookmark.Url)
//line view/home.qtpl:9
		qw422016.N().S(`">`)
//line view/home.qtpl:9
		qw422016.E().S(bookmark.Title)
//line view/home.qtpl:9
		qw422016.N().S(`</a>
        </li>
      `)
//line view/home.qtpl:11
	}
//line view/home.qtpl:11
	qw422016.N().S(`
    </ul>
  </div>
`)
//line view/home.qtpl:14
}

//line view/home.qtpl:14
func WriteHome(qq422016 qtio422016.Writer, bookmarks []presenter.Bookmark) {
//line view/home.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/home.qtpl:14
	StreamHome(qw422016, bookmarks)
//line view/home.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line view/home.qtpl:14
}

//line view/home.qtpl:14
func Home(bookmarks []presenter.Bookmark) string {
//line view/home.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line view/home.qtpl:14
	WriteHome(qb422016, bookmarks)
//line view/home.qtpl:14
	qs422016 := string(qb422016.B)
//line view/home.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line view/home.qtpl:14
	return qs422016
//line view/home.qtpl:14
}
