// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/layout.qtpl:1
package view

//line view/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/layout.qtpl:1
func StreamLayout(qw422016 *qt422016.Writer, title string, content string) {
//line view/layout.qtpl:1
	qw422016.N().S(`
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <title>`)
//line view/layout.qtpl:7
	qw422016.E().S(title)
//line view/layout.qtpl:7
	qw422016.N().S(`</title>
      <link rel="stylesheet" type="text/css" href="/css/tailwind-2.min.css">
      <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>
    <body>
      `)
//line view/layout.qtpl:12
	qw422016.N().S(content)
//line view/layout.qtpl:12
	qw422016.N().S(`
    </body>
  </html>
`)
//line view/layout.qtpl:15
}

//line view/layout.qtpl:15
func WriteLayout(qq422016 qtio422016.Writer, title string, content string) {
//line view/layout.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/layout.qtpl:15
	StreamLayout(qw422016, title, content)
//line view/layout.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line view/layout.qtpl:15
}

//line view/layout.qtpl:15
func Layout(title string, content string) string {
//line view/layout.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line view/layout.qtpl:15
	WriteLayout(qb422016, title, content)
//line view/layout.qtpl:15
	qs422016 := string(qb422016.B)
//line view/layout.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line view/layout.qtpl:15
	return qs422016
//line view/layout.qtpl:15
}
