// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/login.qtpl:1
package view

//line view/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/login.qtpl:1
func StreamLogin(qw422016 *qt422016.Writer, siteName string, errors []string) {
//line view/login.qtpl:1
	qw422016.N().S(`
  <div class="container mx-auto flex flex-col items-stretch p-2">
    <h1 class="text-xl text-center my-2">`)
//line view/login.qtpl:3
	qw422016.E().S(siteName)
//line view/login.qtpl:3
	qw422016.N().S(`</h1>
    <div class="border rounded-sm mt-4 p-2 lg:p-4 w-full lg:w-1/3 mx-auto bg-gray-100">
      <h3 class="text-2xl text-center my-1">Login</h3>
      <form action="/login" method="post">
        <div class="flex flex-col mt-2">
          `)
//line view/login.qtpl:8
	if len(errors) > 0 {
//line view/login.qtpl:8
		qw422016.N().S(`
            <ul class="border p-2 rounded-sm border-red-400 border-dashed">
              `)
//line view/login.qtpl:10
		for _, err := range errors {
//line view/login.qtpl:10
			qw422016.N().S(`
                <li class="font-base text-red-400">`)
//line view/login.qtpl:11
			qw422016.E().S(err)
//line view/login.qtpl:11
			qw422016.N().S(`</li>
              `)
//line view/login.qtpl:12
		}
//line view/login.qtpl:12
		qw422016.N().S(`
            </ul>
          `)
//line view/login.qtpl:14
	}
//line view/login.qtpl:14
	qw422016.N().S(`
          <div class="my-1 flex flex-col">
            <label for="username" class="text-base font-bold">Username</label>
            <input type="text" class="text-lg border rounded p-1 my-2" id="username" name="username">
          </div>
          <div class="my-1 flex flex-col">
            <label for="password" class="text-base font-bold">Password</label>
            <input type="password" class="text-lg border rounded p-1 my-2" id="password" name="password">
          </div>
          <input type="submit" class="bg-green-600 hover:bg-green-800 text-white font-bold mt-2 py-2 px-4 rounded-sm" value="Login">
        </div>
      </form>
    </div>
  </div>
`)
//line view/login.qtpl:28
}

//line view/login.qtpl:28
func WriteLogin(qq422016 qtio422016.Writer, siteName string, errors []string) {
//line view/login.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/login.qtpl:28
	StreamLogin(qw422016, siteName, errors)
//line view/login.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line view/login.qtpl:28
}

//line view/login.qtpl:28
func Login(siteName string, errors []string) string {
//line view/login.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line view/login.qtpl:28
	WriteLogin(qb422016, siteName, errors)
//line view/login.qtpl:28
	qs422016 := string(qb422016.B)
//line view/login.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line view/login.qtpl:28
	return qs422016
//line view/login.qtpl:28
}
