// Code generated by qtc from "settings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/settings.qtpl:1
package view

//line view/settings.qtpl:1
import "github.com/sparkymat/archmark/localize"

//line view/settings.qtpl:2
import "github.com/sparkymat/archmark/presenter"

//line view/settings.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/settings.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/settings.qtpl:4
func StreamSettings(qw422016 *qt422016.Writer, localizer localize.API, lang localize.Language, csrfToken string, languages []presenter.Language) {
//line view/settings.qtpl:4
	qw422016.N().S(`
  <div>
    <form action="/settings" method="POST">
      <input type="hidden" name="csrf" value="`)
//line view/settings.qtpl:7
	qw422016.E().S(csrfToken)
//line view/settings.qtpl:7
	qw422016.N().S(`">
      <div class="container mx-auto mt-8 flex flex-col content-stretch">
        <h3 class="text-2xl text-light py-2 border-b">Language</h3>
        <div class="mt-4 flex flex-row flex-grow items-center">
          <label for="language" class="text-lg">`)
//line view/settings.qtpl:11
	qw422016.E().S(localizer.Lookup(lang, localize.SelectLanguage))
//line view/settings.qtpl:11
	qw422016.N().S(`</label>
          <div class="flex-grow"></div>
          <select id="language" name="language" class="text-xl p-2 border-b-2 bg-transparent border-dashed">
            `)
//line view/settings.qtpl:14
	for _, language := range languages {
//line view/settings.qtpl:14
		qw422016.N().S(`
              <option value="`)
//line view/settings.qtpl:15
		qw422016.E().S(language.Value)
//line view/settings.qtpl:15
		qw422016.N().S(`">`)
//line view/settings.qtpl:15
		qw422016.E().S(language.Label)
//line view/settings.qtpl:15
		qw422016.N().S(`</option>
            `)
//line view/settings.qtpl:16
	}
//line view/settings.qtpl:16
	qw422016.N().S(`
          </select>
        </div>
        <div class="mt-16 flex flex-row justify-end">
          <input type="submit" class="text-l text-white bg-gray-600 hover:bg-gray-800 rounded shadow-md px-8 py-2 ml-4" value="`)
//line view/settings.qtpl:20
	qw422016.E().S(localizer.Lookup(lang, localize.SaveSettings))
//line view/settings.qtpl:20
	qw422016.N().S(`" />
        </div>
      </div>
    </form>
  </div>
`)
//line view/settings.qtpl:25
}

//line view/settings.qtpl:25
func WriteSettings(qq422016 qtio422016.Writer, localizer localize.API, lang localize.Language, csrfToken string, languages []presenter.Language) {
//line view/settings.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/settings.qtpl:25
	StreamSettings(qw422016, localizer, lang, csrfToken, languages)
//line view/settings.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line view/settings.qtpl:25
}

//line view/settings.qtpl:25
func Settings(localizer localize.API, lang localize.Language, csrfToken string, languages []presenter.Language) string {
//line view/settings.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line view/settings.qtpl:25
	WriteSettings(qb422016, localizer, lang, csrfToken, languages)
//line view/settings.qtpl:25
	qs422016 := string(qb422016.B)
//line view/settings.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line view/settings.qtpl:25
	return qs422016
//line view/settings.qtpl:25
}
