// Code generated by qtc from "setup.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/setup.qtpl:1
package view

//line view/setup.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/setup.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/setup.qtpl:1
func StreamSetup(qw422016 *qt422016.Writer, siteName string) {
//line view/setup.qtpl:1
	qw422016.N().S(`
  <div class="container mx-auto flex flex-col items-stretch p-2">
    <h1 class="text-xl text-center my-2">`)
//line view/setup.qtpl:3
	qw422016.E().S(siteName)
//line view/setup.qtpl:3
	qw422016.N().S(`</h1>
    <h3 class="text-2xl text-center my-2">Setup</h3>
    <p>Set up your new instance of archmark!</p>
    <form>
      <div class="flex flex-col mt-4">
        <div class="my-2 flex flex-col flex-grow">
          <label for="site_name" class="text-base">Site name</label>
          <input type="text" class="text-lg border rounded p-1 my-2" id="site_name" name="site_name" value="`)
//line view/setup.qtpl:10
	qw422016.E().S(siteName)
//line view/setup.qtpl:10
	qw422016.N().S(`" autofocus>
        </div>
        <div class="my-2 flex flex-col">
          <label for="admin_password" class="text-base">Admin password</label>
          <input type="password" class="text-lg border rounded p-1 my-2" id="admin_password" name="admin_password">
        </div>
        <div class="my-2 flex flex-col">
          <label for="admin_password_confirmation" class="text-base">Confirm admin password</label>
          <input type="password" class="text-lg border rounded p-1 my-2" id="admin_password_confirmation" name="admin_password_confirmation">
        </div>
        <input type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-sm" value="Initialise">
      </div>
    </form>
  </div>
`)
//line view/setup.qtpl:24
}

//line view/setup.qtpl:24
func WriteSetup(qq422016 qtio422016.Writer, siteName string) {
//line view/setup.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/setup.qtpl:24
	StreamSetup(qw422016, siteName)
//line view/setup.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line view/setup.qtpl:24
}

//line view/setup.qtpl:24
func Setup(siteName string) string {
//line view/setup.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line view/setup.qtpl:24
	WriteSetup(qb422016, siteName)
//line view/setup.qtpl:24
	qs422016 := string(qb422016.B)
//line view/setup.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line view/setup.qtpl:24
	return qs422016
//line view/setup.qtpl:24
}
