// Code generated by qtc from "show_error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/show_error.qtpl:1
package view

//line view/show_error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/show_error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/show_error.qtpl:1
func StreamShowError(qw422016 *qt422016.Writer, message string) {
//line view/show_error.qtpl:1
	qw422016.N().S(`
  <div class="container mx-auto">
    <div class="flex flex-col items-center mt-16">
      <p class="border border-dashed border-gray-400 py-4 px-8 text-xl text-red-600">`)
//line view/show_error.qtpl:4
	qw422016.E().S(message)
//line view/show_error.qtpl:4
	qw422016.N().S(`</p>
    </div>
  </div>
`)
//line view/show_error.qtpl:7
}

//line view/show_error.qtpl:7
func WriteShowError(qq422016 qtio422016.Writer, message string) {
//line view/show_error.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/show_error.qtpl:7
	StreamShowError(qw422016, message)
//line view/show_error.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line view/show_error.qtpl:7
}

//line view/show_error.qtpl:7
func ShowError(message string) string {
//line view/show_error.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line view/show_error.qtpl:7
	WriteShowError(qb422016, message)
//line view/show_error.qtpl:7
	qs422016 := string(qb422016.B)
//line view/show_error.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line view/show_error.qtpl:7
	return qs422016
//line view/show_error.qtpl:7
}
